[mysql]
dsn = "root:123456@tcp(127.0.0.1:3306)/likegochat?parseTime=true&charset=utf8mb4&loc=Local"

[logic]
grpc_addr = "127.0.0.1:50051"

[api]
http_addr = "127.0.0.1:8080"
logic_grpc_addr = "127.0.0.1:50051"

[redis]
addr = "127.0.0.1:6379"
password = ""
db = 0

[session]
session_ttl_seconds = 2592000       # 30天（服务端 session 过期）

[logger]
log_file_path = "./logs/dev.log"
log_file_size = 10
log_file_backups = 5
log_file_age = 7
log_file_level = "debug"