[mysql]
dsn = "root:123456@tcp(127.0.0.1:3306)/likegochat?parseTime=true&charset=utf8mb4&loc=Local"

[logic]
grpc_addr = "127.0.0.1:50051"
chat_topic = "chat_messages"
[api]
http_addr = "127.0.0.1:8080"
logic_grpc_addr = "127.0.0.1:50051"

[redis]
redis_addr = "127.0.0.1:6379"
redis_password = "sudo"
redis_db = 0

[session]
session_ttl_seconds = 2592000       # 30天（服务端 session 过期）

[logger]
log_file_path = "./logs/dev.log"
log_file_size = 10
log_file_backups = 5
log_file_age = 7
log_file_level = "debug"

[connect1]
connect_grpc_addr = "127.0.0.1:50052"
connec_http_addr = "127.0.0.1:8081"

[connect2]
connect_grpc_addr = "127.0.0.1:50053"
connec_http_addr = "127.0.0.1:8082"


[kafka]
# Kafka 节点地址列表
kafka_brokers = ["127.0.0.1:9092"]
# 单人消费组名称
kafka__single_consumer_group = "singlechat_task_group"
# 单人聊天Topic
kafka__chat_topic = "chat_messages"
# 多人消费组名称
kafka__group_consumer_group = "groupchat_task_group"
# 多人聊天Topic
kafka__group_chat_topic = "group_chat_messages"
# 多人聊天模式阈值
small_group_max_members = 200
# kafka版本
kafka_version = "3.8.1"