// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: proto/connect.proto

package connectpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PushMsgRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	ToUserId int64                  `protobuf:"varint,1,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`
	// 序列化后的具体聊天内容，connect层不负责数据的反序列化，反序列化放到终端做
	Payload       []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushMsgRequest) Reset() {
	*x = PushMsgRequest{}
	mi := &file_proto_connect_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushMsgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushMsgRequest) ProtoMessage() {}

func (x *PushMsgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connect_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushMsgRequest.ProtoReflect.Descriptor instead.
func (*PushMsgRequest) Descriptor() ([]byte, []int) {
	return file_proto_connect_proto_rawDescGZIP(), []int{0}
}

func (x *PushMsgRequest) GetToUserId() int64 {
	if x != nil {
		return x.ToUserId
	}
	return 0
}

func (x *PushMsgRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type PushAllRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 消息所属的群组ID
	GroupId int64 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	// 序列化消息内容
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	// 目标用户ID数组
	UserIds       []int64 `protobuf:"varint,3,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushAllRequest) Reset() {
	*x = PushAllRequest{}
	mi := &file_proto_connect_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushAllRequest) ProtoMessage() {}

func (x *PushAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connect_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushAllRequest.ProtoReflect.Descriptor instead.
func (*PushAllRequest) Descriptor() ([]byte, []int) {
	return file_proto_connect_proto_rawDescGZIP(), []int{1}
}

func (x *PushAllRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *PushAllRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PushAllRequest) GetUserIds() []int64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type PushMsgReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushMsgReply) Reset() {
	*x = PushMsgReply{}
	mi := &file_proto_connect_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushMsgReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushMsgReply) ProtoMessage() {}

func (x *PushMsgReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connect_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushMsgReply.ProtoReflect.Descriptor instead.
func (*PushMsgReply) Descriptor() ([]byte, []int) {
	return file_proto_connect_proto_rawDescGZIP(), []int{2}
}

func (x *PushMsgReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type BroadcastRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	FromUserId    int64                  `protobuf:"varint,2,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastRoomRequest) Reset() {
	*x = BroadcastRoomRequest{}
	mi := &file_proto_connect_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastRoomRequest) ProtoMessage() {}

func (x *BroadcastRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connect_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastRoomRequest.ProtoReflect.Descriptor instead.
func (*BroadcastRoomRequest) Descriptor() ([]byte, []int) {
	return file_proto_connect_proto_rawDescGZIP(), []int{3}
}

func (x *BroadcastRoomRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *BroadcastRoomRequest) GetFromUserId() int64 {
	if x != nil {
		return x.FromUserId
	}
	return 0
}

func (x *BroadcastRoomRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type BroadcastRoomReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Fanout        int32                  `protobuf:"varint,2,opt,name=fanout,proto3" json:"fanout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastRoomReply) Reset() {
	*x = BroadcastRoomReply{}
	mi := &file_proto_connect_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastRoomReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastRoomReply) ProtoMessage() {}

func (x *BroadcastRoomReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connect_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastRoomReply.ProtoReflect.Descriptor instead.
func (*BroadcastRoomReply) Descriptor() ([]byte, []int) {
	return file_proto_connect_proto_rawDescGZIP(), []int{4}
}

func (x *BroadcastRoomReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BroadcastRoomReply) GetFanout() int32 {
	if x != nil {
		return x.Fanout
	}
	return 0
}

var File_proto_connect_proto protoreflect.FileDescriptor

const file_proto_connect_proto_rawDesc = "" +
	"\n" +
	"\x13proto/connect.proto\x12\tconnectpb\"H\n" +
	"\x0ePushMsgRequest\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\x01 \x01(\x03R\btoUserId\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"`\n" +
	"\x0ePushAllRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x19\n" +
	"\buser_ids\x18\x03 \x03(\x03R\auserIds\"(\n" +
	"\fPushMsgReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"m\n" +
	"\x14BroadcastRoomRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12 \n" +
	"\ffrom_user_id\x18\x02 \x01(\x03R\n" +
	"fromUserId\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"F\n" +
	"\x12BroadcastRoomReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06fanout\x18\x02 \x01(\x05R\x06fanout2\xe6\x01\n" +
	"\x0eConnectService\x12=\n" +
	"\aPushMsg\x12\x19.connectpb.PushMsgRequest\x1a\x17.connectpb.PushMsgReply\x12O\n" +
	"\rBroadcastRoom\x12\x1f.connectpb.BroadcastRoomRequest\x1a\x1d.connectpb.BroadcastRoomReply\x12D\n" +
	"\x0ePushMsgToUsers\x12\x19.connectpb.PushAllRequest\x1a\x17.connectpb.PushMsgReplyB-Z+./internal/common/proto/connectpb;connectpbb\x06proto3"

var (
	file_proto_connect_proto_rawDescOnce sync.Once
	file_proto_connect_proto_rawDescData []byte
)

func file_proto_connect_proto_rawDescGZIP() []byte {
	file_proto_connect_proto_rawDescOnce.Do(func() {
		file_proto_connect_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_connect_proto_rawDesc), len(file_proto_connect_proto_rawDesc)))
	})
	return file_proto_connect_proto_rawDescData
}

var file_proto_connect_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_connect_proto_goTypes = []any{
	(*PushMsgRequest)(nil),       // 0: connectpb.PushMsgRequest
	(*PushAllRequest)(nil),       // 1: connectpb.PushAllRequest
	(*PushMsgReply)(nil),         // 2: connectpb.PushMsgReply
	(*BroadcastRoomRequest)(nil), // 3: connectpb.BroadcastRoomRequest
	(*BroadcastRoomReply)(nil),   // 4: connectpb.BroadcastRoomReply
}
var file_proto_connect_proto_depIdxs = []int32{
	0, // 0: connectpb.ConnectService.PushMsg:input_type -> connectpb.PushMsgRequest
	3, // 1: connectpb.ConnectService.BroadcastRoom:input_type -> connectpb.BroadcastRoomRequest
	1, // 2: connectpb.ConnectService.PushMsgToUsers:input_type -> connectpb.PushAllRequest
	2, // 3: connectpb.ConnectService.PushMsg:output_type -> connectpb.PushMsgReply
	4, // 4: connectpb.ConnectService.BroadcastRoom:output_type -> connectpb.BroadcastRoomReply
	2, // 5: connectpb.ConnectService.PushMsgToUsers:output_type -> connectpb.PushMsgReply
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_connect_proto_init() }
func file_proto_connect_proto_init() {
	if File_proto_connect_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_connect_proto_rawDesc), len(file_proto_connect_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_connect_proto_goTypes,
		DependencyIndexes: file_proto_connect_proto_depIdxs,
		MessageInfos:      file_proto_connect_proto_msgTypes,
	}.Build()
	File_proto_connect_proto = out.File
	file_proto_connect_proto_goTypes = nil
	file_proto_connect_proto_depIdxs = nil
}
